import { spawnSync } from "node:child_process"
import { existsSync, mkdirSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { writeAtomicFile } from "../lib/fs-atomic.js"
import { hypothesisDir } from "./propose.js"
import type { HarnessHypothesis } from "../contracts/schemas.js"

export type ExecResult = Readonly<{
  status: number
  stdout: string
  stderr: string
}>

export type ExecFn = (
  bin: string,
  args: readonly string[],
  opts?: Readonly<{ cwd?: string }>,
) => ExecResult

export const defaultExec: ExecFn = (bin, args, opts) => {
  const result = spawnSync(bin, [...args], {
    cwd: opts?.cwd,
    encoding: "utf8",
  })
  return {
    status: result.status ?? 1,
    stdout: result.stdout ?? "",
    stderr: result.stderr ?? "",
  }
}

export type OpenPullRequestOptions = Readonly<{
  worktreePath: string
  branch: string
  baseBranch: string
  title: string
  body: string
  push: boolean
  createPr: boolean
  exec?: ExecFn
}>

export type OpenPullRequestResult = Readonly<{
  pushed: boolean
  prUrl?: string
  prCreated: boolean
  commitSha?: string
  skippedReason?: string
}>

/** Stage allowlisted paths, commit, optionally push + open PR. Never merges. */
export function openHarnessPullRequest(
  opts: OpenPullRequestOptions,
): OpenPullRequestResult {
  const exec = opts.exec ?? defaultExec

  const status = exec("git", ["status", "--porcelain"], { cwd: opts.worktreePath })
  if (status.status !== 0) {
    throw new Error(`git status failed: ${status.stderr}`)
  }
  if (!status.stdout.trim()) {
    return { pushed: false, prCreated: false, skippedReason: "no changes to commit" }
  }

  const stageRoots = (["agent", "docs"] as const).filter((name) =>
    existsSync(join(opts.worktreePath, name)),
  )
  if (stageRoots.length === 0) {
    return { pushed: false, prCreated: false, skippedReason: "no allowlisted roots to stage" }
  }
  const add = exec("git", ["add", "-A", "--", ...stageRoots], { cwd: opts.worktreePath })
  if (add.status !== 0) throw new Error(`git add failed: ${add.stderr}`)

  // Drop accidental brief if staged
  exec("git", ["reset", "HEAD", "--", "HARNESS_BRIEF.md"], { cwd: opts.worktreePath })

  const commit = exec(
    "git",
    ["commit", "-m", opts.title],
    { cwd: opts.worktreePath },
  )
  if (commit.status !== 0 && !/nothing to commit/iu.test(commit.stdout + commit.stderr)) {
    throw new Error(`git commit failed: ${commit.stderr || commit.stdout}`)
  }

  const sha = exec("git", ["rev-parse", "HEAD"], { cwd: opts.worktreePath })
  const commitSha = sha.status === 0 ? sha.stdout.trim() : undefined

  if (!opts.push) {
    return { pushed: false, prCreated: false, ...(commitSha ? { commitSha } : {}) }
  }

  const push = exec(
    "git",
    ["push", "-u", "origin", `HEAD:refs/heads/${opts.branch}`],
    { cwd: opts.worktreePath },
  )
  if (push.status !== 0) {
    throw new Error(`git push failed: ${push.stderr || push.stdout}`)
  }

  if (!opts.createPr) {
    return { pushed: true, prCreated: false, ...(commitSha ? { commitSha } : {}) }
  }

  const pr = exec(
    "gh",
    [
      "pr",
      "create",
      "--base",
      opts.baseBranch,
      "--head",
      opts.branch,
      "--title",
      opts.title,
      "--body",
      opts.body,
    ],
    { cwd: opts.worktreePath },
  )
  if (pr.status !== 0) {
    // PR may already exist
    if (/already exists/iu.test(pr.stderr + pr.stdout)) {
      const view = exec(
        "gh",
        ["pr", "view", opts.branch, "--json", "url", "-q", ".url"],
        { cwd: opts.worktreePath },
      )
      return {
        pushed: true,
        prCreated: false,
        ...(view.status === 0 && view.stdout.trim()
          ? { prUrl: view.stdout.trim() }
          : {}),
        ...(commitSha ? { commitSha } : {}),
        skippedReason: "pr already exists",
      }
    }
    throw new Error(`gh pr create failed: ${pr.stderr || pr.stdout}`)
  }

  const prUrl = pr.stdout.trim().split("\n").filter(Boolean).at(-1)
  return {
    pushed: true,
    prCreated: true,
    ...(prUrl ? { prUrl } : {}),
    ...(commitSha ? { commitSha } : {}),
  }
}

export async function applyDecisionPolicyStub(opts: Readonly<{
  worktreePath: string
  hypothesis: HarnessHypothesis
}>): Promise<string> {
  const dir = join(opts.worktreePath, "agent", "skills", "harness-experiment")
  mkdirSync(dir, { recursive: true, mode: 0o700 })
  const path = join(dir, "SKILL.md")
  const body = [
    `# harness-experiment`,
    "",
    "Bounded decision-policy experiment generated by the harness improvement job.",
    "Host-owned; do not treat as runtime instructions for unrelated skills.",
    "",
    `## Hypothesis`,
    "",
    `- id: ${opts.hypothesis.hypothesisId}`,
    `- epoch: ${opts.hypothesis.epochId}`,
    `- manifest: ${opts.hypothesis.manifestHash}`,
    `- primary_metric: ${opts.hypothesis.primaryMetric}`,
    "",
    "## Rationale",
    "",
    opts.hypothesis.rationale,
    "",
    "## Safety floors",
    "",
    "```json",
    JSON.stringify(opts.hypothesis.safetyFloors, null, 2),
    "```",
    "",
    "## Operator",
    "",
    "Merge the PR only after review. Canary remains a separate explicit step.",
    "",
  ].join("\n")
  writeFileSync(path, body, { mode: 0o600 })
  return path
}

export async function persistPrReceipt(opts: Readonly<{
  archiveRoot: string
  hypothesisId: string
  result: OpenPullRequestResult
  branch: string
  nowIso: string
}>): Promise<void> {
  const dir = hypothesisDir(opts.archiveRoot, opts.hypothesisId)
  await writeAtomicFile(
    join(dir, "pr.json"),
    `${JSON.stringify({
      schema: 1,
      hypothesisId: opts.hypothesisId,
      branch: opts.branch,
      createdAt: opts.nowIso,
      ...opts.result,
    }, null, 2)}\n`,
  )
}

export function assertRepoRoot(path: string): void {
  if (!existsSync(join(path, ".git")) && !existsSync(join(path, "package.json"))) {
    throw new Error(`Not a trenchcoat repo root: ${path}`)
  }
}
