import { existsSync, readFileSync } from "node:fs"
import { join } from "node:path"
import {
  ResearchQueueEntrySchema,
  ResearchQueueFileSchema,
  type ResearchQueueEntry,
  type ResearchQueueFile,
} from "../contracts/schemas.js"
import { ensureArchive, writeJsonRecordFsync } from "../lib/archive.js"
import { isGenericChainSymbol, GENERIC_CHAIN_SYMBOL_REASON } from "../lib/narrative-tickers.js"
import { StateStore } from "../lib/state.js"

export const GENERIC_SYMBOL_REPAIR_ID = "generic-chain-symbol-v1"

function isAutoGeneratedNarrativeEntry(entry: ResearchQueueEntry): boolean {
  return entry.trigger === "narrative"
    && entry.queueId.startsWith("rq-narrative-")
    && entry.enqueuedBy.startsWith("narrative:")
}

function subjectIsReservedGeneric(entry: ResearchQueueEntry): boolean {
  if (isGenericChainSymbol(entry.subject)) return true
  if (entry.symbolDisplay && isGenericChainSymbol(entry.symbolDisplay)) return true
  return false
}

/** Mark only auto-generated ambiguous narrative generics as rejected; never delete history */
export function repairGenericNarrativeQueueEntries(
  file: ResearchQueueFile,
  nowIso: string,
): Readonly<{
  next: ResearchQueueFile
  repaired: readonly ResearchQueueEntry[]
}> {
  const repaired: ResearchQueueEntry[] = []
  const entries = file.entries.map((entry) => {
    if (entry.status !== "ambiguous") return entry
    if (!isAutoGeneratedNarrativeEntry(entry)) return entry
    if (!subjectIsReservedGeneric(entry)) return entry
    const next: ResearchQueueEntry = ResearchQueueEntrySchema.parse({
      ...entry,
      status: "rejected",
      reason: GENERIC_CHAIN_SYMBOL_REASON,
      priority: 0,
    })
    repaired.push({
      ...next,
      reason: `${GENERIC_CHAIN_SYMBOL_REASON}; repairedAt=${nowIso}`.slice(0, 280),
    })
    return {
      ...next,
      reason: GENERIC_CHAIN_SYMBOL_REASON,
    }
  })
  return {
    next: ResearchQueueFileSchema.parse({ ...file, schema: 1, entries }),
    repaired,
  }
}

export function genericSymbolRepairReceiptPath(archiveRoot: string): string {
  return join(archiveRoot, "migrations", `${GENERIC_SYMBOL_REPAIR_ID}.json`)
}

export type GenericSymbolRepairReport = Readonly<{
  schema: 1
  migrationId: typeof GENERIC_SYMBOL_REPAIR_ID
  repairedAt: string
  repairedCount: number
  queueIds: readonly string[]
  skipped: boolean
  reason?: string
}>

/**
 * One-time state repair: reject historical ambiguous narrative generics and archive a receipt.
 * Idempotent via archive receipt presence.
 */
export async function migrateGenericNarrativeResearchQueue(args: Readonly<{
  agentRoot: string
  archiveRoot: string
  nowIso?: string
  force?: boolean
}>): Promise<GenericSymbolRepairReport> {
  const nowIso = args.nowIso ?? new Date().toISOString()
  const receiptPath = genericSymbolRepairReceiptPath(args.archiveRoot)
  if (!args.force && existsSync(receiptPath)) {
    try {
      const prior = JSON.parse(readFileSync(receiptPath, "utf8")) as GenericSymbolRepairReport
      return {
        schema: 1,
        migrationId: GENERIC_SYMBOL_REPAIR_ID,
        repairedAt: prior.repairedAt ?? nowIso,
        repairedCount: prior.repairedCount ?? 0,
        queueIds: prior.queueIds ?? [],
        skipped: true,
        reason: "receipt-present",
      }
    } catch {
      // Fall through and rewrite a valid receipt
    }
  }

  const state = new StateStore(join(args.agentRoot, "state"))
  const queue = state.loadResearchQueue()
  const { next, repaired } = repairGenericNarrativeQueueEntries(queue, nowIso)
  if (repaired.length > 0) {
    await state.saveResearchQueue(next)
  }

  const report: GenericSymbolRepairReport = {
    schema: 1,
    migrationId: GENERIC_SYMBOL_REPAIR_ID,
    repairedAt: nowIso,
    repairedCount: repaired.length,
    queueIds: repaired.map((entry) => entry.queueId),
    skipped: false,
  }
  const layout = await ensureArchive(args.archiveRoot)
  await writeJsonRecordFsync(
    join(layout.root, "migrations", `${GENERIC_SYMBOL_REPAIR_ID}.json`),
    report as never,
  )
  return report
}
