/**
 * Load + validate chains/*.json manifests and emit src/lib/chains.generated.ts
 * Usage: pnpm exec tsx scripts/generate-chains.ts [--check]
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs"
import { join } from "node:path"
import { ChainManifestSchema, type ChainManifest } from "../src/lib/chain-manifest.js"

const root = process.cwd()
const chainsDir = join(root, "chains")
const outPath = join(root, "src", "lib", "chains.generated.ts")
const checkOnly = process.argv.includes("--check")

function loadManifests(): ChainManifest[] {
  if (!existsSync(chainsDir)) throw new Error(`missing chains/ at ${chainsDir}`)
  const files = readdirSync(chainsDir).filter((f) => f.endsWith(".json")).sort()
  if (files.length === 0) throw new Error("chains/ has no manifests")
  const out: ChainManifest[] = []
  const seenSlugs = new Set<string>()
  const seenAliases = new Set<string>()
  for (const file of files) {
    const raw = JSON.parse(readFileSync(join(chainsDir, file), "utf8"))
    const m = ChainManifestSchema.parse(raw)
    if (`${m.slug}.json` !== file) {
      throw new Error(`manifest filename must be ${m.slug}.json (got ${file})`)
    }
    if (seenSlugs.has(m.slug)) throw new Error(`duplicate slug ${m.slug}`)
    seenSlugs.add(m.slug)
    if (seenAliases.has(m.slug)) throw new Error(`slug ${m.slug} collides with alias`)
    seenAliases.add(m.slug)
    for (const alias of m.aliases) {
      if (seenAliases.has(alias) || seenSlugs.has(alias)) {
        throw new Error(`duplicate alias ${alias}`)
      }
      seenAliases.add(alias)
    }
    out.push(m)
  }
  return out
}

function render(manifests: readonly ChainManifest[]): string {
  const slugs = manifests.map((m) => m.slug)
  const lines: string[] = [
    "// AUTO-GENERATED by scripts/generate-chains.ts — do not edit by hand",
    "",
    `export const GENERATED_CHAIN_SLUGS = ${JSON.stringify(slugs)} as const`,
    "export type GeneratedChainSlug = typeof GENERATED_CHAIN_SLUGS[number]",
    "",
    "export const GENERATED_CHAIN_REGISTRY = Object.freeze([",
  ]
  for (const m of manifests) {
    const scanner = m.securityScanner
      ? m.securityScanner.kind === "goplus"
        ? `{ kind: "goplus" as const, chainId: ${JSON.stringify(m.securityScanner.chainId)} }`
        : `{ kind: "rugcheck" as const }`
      : "undefined"
    lines.push("  Object.freeze({")
    lines.push(`    slug: ${JSON.stringify(m.slug)},`)
    lines.push(`    display: ${JSON.stringify(m.display)},`)
    lines.push(`    family: ${JSON.stringify(m.family)} as const,`)
    lines.push(`    aliases: Object.freeze(${JSON.stringify(m.aliases)}) as readonly string[],`)
    lines.push(`    geckoterminalNetwork: ${JSON.stringify(m.geckoterminalNetwork)},`)
    lines.push(`    dexscreenerChainId: ${JSON.stringify(m.dexscreenerChainId)},`)
    if (m.securityScanner) {
      lines.push(`    securityScanner: ${scanner},`)
    }
    lines.push(`    nativeBenchmark: ${JSON.stringify(m.nativeBenchmark)},`)
    lines.push(`    addressFormat: ${JSON.stringify(m.addressFormat)} as const,`)
    lines.push(`    walletTracking: ${JSON.stringify(m.walletTracking)} as const,`)
    if (m.evmChainId != null) {
      lines.push(`    evmChainId: ${m.evmChainId},`)
    }
    lines.push(`    quoteAssets: Object.freeze({`)
    lines.push(`      acceptNative: ${m.quoteAssets.acceptNative},`)
    lines.push(`      allowlist: Object.freeze(${JSON.stringify(m.quoteAssets.allowlist)}) as readonly string[],`)
    lines.push(`    }),`)
    lines.push(`    capabilities: Object.freeze(${JSON.stringify(m.capabilities)}),`)
    lines.push("  }),")
  }
  lines.push("] as const)")
  lines.push("")
  lines.push("export const GENERATED_ALIAS_TO_SLUG: Readonly<Record<string, string>> = Object.freeze({")
  for (const m of manifests) {
    lines.push(`  ${JSON.stringify(m.slug)}: ${JSON.stringify(m.slug)},`)
    for (const alias of m.aliases) {
      lines.push(`  ${JSON.stringify(alias)}: ${JSON.stringify(m.slug)},`)
    }
  }
  // eth is both ethereum alias and gecko network for ethereum — already covered
  lines.push("})")
  lines.push("")
  return `${lines.join("\n")}\n`
}

const manifests = loadManifests()
const rendered = render(manifests)

if (checkOnly) {
  if (!existsSync(outPath)) {
    console.error("chains.generated.ts missing — run pnpm generate:chains")
    process.exit(1)
  }
  const existing = readFileSync(outPath, "utf8")
  if (existing !== rendered) {
    console.error("chains.generated.ts is stale — run pnpm generate:chains")
    process.exit(1)
  }
  console.log(`chains.generated.ts up to date (${manifests.length} chains)`)
  process.exit(0)
}

writeFileSync(outPath, rendered, { mode: 0o644 })
console.log(`wrote ${outPath} (${manifests.length} chains)`)
