import { describe, expect, it } from "vitest"
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { StateStore } from "../../src/lib/state.js"
import {
  extractNarrativeTickers,
  parseDecisionRows,
  reconcileIndex,
  reconcileIndexWithReceipt,
  hashIndexMd,
  resolveSealedNarrativeFreshness,
} from "../../src/orchestrator/index-reconcile.js"
import { removeWatchlistEntry } from "../../src/orchestrator/watchlist-remove.js"
import { SnapshotWriter } from "../../src/lib/snapshot.js"
import { ensureArchive } from "../../src/lib/archive.js"

const NOW = "2026-07-18T12:00:00.000Z"
const TOKEN = "0xFf8104251E7761163faC3211eF5583FB3F8583d6"

describe("reconcileIndex", () => {
  it("writes deterministic host-owned INDEX from watchlist", async () => {
    const root = mkdtempSync(join(tmpdir(), "tc-index-"))
    mkdirSync(join(root, "state"), { recursive: true })
    const state = new StateStore(join(root, "state"))
    await state.saveWatchlist({
      schema: 1,
      entries: [{
        schema: 1,
        identity: {
          chain: "base",
          tokenAddress: TOKEN,
          pairAddress: "0x1111111111111111111111111111111111111111",
          symbolDisplay: "AAA",
          resolution: "resolved",
        },
        status: "watching",
        addedAt: NOW,
        updatedAt: NOW,
        lastDecisionId: "dec-1",
      }],
    })
    await state.appendDecision([
      "## dec-1 — track base:" + TOKEN,
      `- date: ${NOW}  run: t`,
      "- thesis: solid setup",
      "",
    ].join("\n"))
    const report = await reconcileIndex({ agentRoot: root, state, nowIso: NOW })
    const body = readFileSync(join(root, "state", "INDEX.md"), "utf8")
    expect(report.tokenLines).toBe(1)
    expect(body).toContain("$AAA — watching, solid setup")
    expect(body).toContain("Do not edit this file from the model")
  })

  it("includes removed decided tokens and narrative-linked tickers", async () => {
    const root = mkdtempSync(join(tmpdir(), "tc-index-decided-"))
    mkdirSync(join(root, "state", "narratives"), { recursive: true })
    const state = new StateStore(join(root, "state"))
    await state.saveWatchlist({ schema: 1, entries: [] })
    await state.appendDecision([
      "## dec-reppo-ignore — ignore base:" + TOKEN,
      `- date: ${NOW}  run: t`,
      "- thesis: faded",
      "- subject: REPPO",
      "",
      "## dec-reppo-rm — operator-remove base:" + TOKEN,
      `- date: ${NOW}  run: operator-cli`,
      "- subject: REPPO",
      "- reason: cleared",
      "",
    ].join("\n"))
    writeFileSync(
      join(root, "state", "narratives", "log.jsonl"),
      JSON.stringify({
        slug: "hoodrat-meme",
        title: "$HOODRAT and CashCat rotating",
        firstSeen: NOW,
        lastSeen: NOW,
        evidence: ["twitter:@x"],
        stage: "emerging",
      }) + "\n",
    )
    const report = await reconcileIndex({ agentRoot: root, state, nowIso: NOW })
    const body = readFileSync(join(root, "state", "INDEX.md"), "utf8")
    expect(report.tokenLines).toBeGreaterThanOrEqual(2)
    expect(body).toContain("$REPPO — removed")
    expect(body).toContain("$HOODRAT — narrative")
    expect(body).not.toContain("$CashCat — narrative")
    expect(body).not.toContain("(none yet)")
  })

  it("parses decision rows and narrative tickers", () => {
    const rows = parseDecisionRows([
      "## dec-1 — operator-remove base:0xabc",
      "- subject: REPPO",
      "",
    ].join("\n"))
    expect(rows[0]?.verdict).toBe("operator-remove")
    expect(rows[0]?.subject).toBe("REPPO")
    expect(extractNarrativeTickers({
      slug: "x",
      title: "$HOODRAT season",
      firstSeen: NOW,
      lastSeen: NOW,
      evidence: [],
      stage: "emerging",
    })).toContain("HOODRAT")
  })
})

describe("watchlist remove", () => {
  it("refuses open ledger positions and tracking status", async () => {
    const root = mkdtempSync(join(tmpdir(), "tc-remove-"))
    const archive = mkdtempSync(join(tmpdir(), "tc-archive-"))
    mkdirSync(join(root, "state"), { recursive: true })
    const state = new StateStore(join(root, "state"))
    await state.saveWatchlist({
      schema: 1,
      entries: [{
        schema: 1,
        identity: {
          chain: "base",
          tokenAddress: TOKEN,
          pairAddress: "0x1111111111111111111111111111111111111111",
          symbolDisplay: "REPPO",
          resolution: "resolved",
        },
        status: "tracking",
        addedAt: NOW,
        updatedAt: NOW,
      }],
    })
    const refused = await removeWatchlistEntry({
      agentRoot: root,
      archiveRoot: archive,
      identityKey: `base:${TOKEN}`,
      subject: "REPPO",
      reason: "test",
    })
    expect(refused.status).toBe("refused")
    expect(refused.refusedReason).toBe("active-status-use-drop")
  })

  it("removes ignored entry and queue rows with tombstone", async () => {
    const root = mkdtempSync(join(tmpdir(), "tc-remove-ok-"))
    const archive = mkdtempSync(join(tmpdir(), "tc-archive-ok-"))
    mkdirSync(join(root, "state"), { recursive: true })
    const state = new StateStore(join(root, "state"))
    await state.saveWatchlist({
      schema: 1,
      entries: [{
        schema: 1,
        identity: {
          chain: "base",
          tokenAddress: TOKEN,
          pairAddress: "0x1111111111111111111111111111111111111111",
          symbolDisplay: "REPPO",
          resolution: "resolved",
        },
        status: "ignored",
        addedAt: NOW,
        updatedAt: NOW,
        lastDecisionId: "dec-reppo-ignore-20260717200344",
      }],
    })
    await state.saveResearchQueue({
      schema: 1,
      entries: [{
        schema: 1,
        queueId: "rq-1",
        subject: "REPPO",
        chain: "base",
        tokenAddress: TOKEN,
        resolution: "resolved",
        priority: 1,
        firstSeen: NOW,
        enqueuedAt: NOW,
        enqueuedBy: "operator",
        trigger: "operator",
        expiresAt: "2099-01-01T00:00:00.000Z",
        provenance: ["p1"],
        clusterCount: 1,
        security: { status: "pending", flags: [] },
        status: "pending",
        reason: "x",
      }, {
        schema: 1,
        queueId: "rq-2",
        subject: "REPPO",
        resolution: "pending",
        priority: 1,
        firstSeen: NOW,
        enqueuedAt: NOW,
        enqueuedBy: "operator",
        trigger: "social",
        expiresAt: "2099-01-01T00:00:00.000Z",
        provenance: ["p2"],
        clusterCount: 1,
        security: { status: "pending", flags: [] },
        status: "pending",
        reason: "unbound",
      }],
    })
    await state.appendDecision("## dec-reppo-ignore-20260717200344 — ignore base:" + TOKEN + "\n")

    const report = await removeWatchlistEntry({
      agentRoot: root,
      archiveRoot: archive,
      identityKey: `base:${TOKEN}`,
      subject: "REPPO",
      reason: "operator manual review cleared token; remove prior ignored state",
    })
    expect(report.status).toBe("removed")
    expect(report.removedQueueIds).toEqual(expect.arrayContaining(["rq-1", "rq-2"]))
    expect(state.loadWatchlist().entries).toHaveLength(0)
    expect(state.loadResearchQueue().entries).toHaveLength(0)
    expect(state.readDecisions()).toContain("dec-reppo-ignore-20260717200344")
    expect(state.readDecisions()).toContain("operator-remove")
    expect(existsSync(join(root, "state", "INDEX.md"))).toBe(true)
  })
})

describe("index reconcile receipt", () => {
  it("hashes before/after and archives source timestamps", async () => {
    const root = mkdtempSync(join(tmpdir(), "tc-index-receipt-"))
    mkdirSync(join(root, "state", "narratives"), { recursive: true })
    mkdirSync(join(root, "reports", "run-1"), { recursive: true })
    const archiveRoot = join(root, "archive")
    const layout = await ensureArchive(archiveRoot)
    const state = new StateStore(join(root, "state"))
    await state.saveWatchlist({ schema: 1, entries: [] })
    writeFileSync(
      join(root, "state", "INDEX.md"),
      "# INDEX\n\nold\n\n## Tokens\n\n(none yet)\n\n## Narratives\n\n(none yet)\n",
    )
    writeFileSync(
      join(root, "state", "narratives", "log.jsonl"),
      `${JSON.stringify({
        slug: "base-ai",
        title: "$BASE rotating",
        firstSeen: NOW,
        lastSeen: NOW,
        evidence: ["twitter:@x"],
        stage: "emerging",
      })}\n`,
    )

    const before = hashIndexMd(root)
    const receipt = await reconcileIndexWithReceipt({
      agentRoot: root,
      state,
      nowIso: NOW,
      layout,
      runId: "run-1",
      job: "narrative-scan",
      archiveRoot,
      reportDir: join(root, "reports", "run-1"),
    })
    expect(receipt.beforeHash).toBe(before)
    expect(receipt.afterHash).toMatch(/^sha256:/)
    expect(receipt.changed).toBe(true)
    expect(receipt.sources.narrativesLatestLastSeen).toBe(NOW)
    expect(receipt.sources.narrativesCount).toBe(1)
    expect(receipt.freshnessNote).toContain("sealed complete")
    expect(existsSync(join(archiveRoot, "runs", "run-1", "index-reconcile-receipt.json"))).toBe(true)
    expect(existsSync(join(root, "reports", "run-1", "index-reconcile-receipt.json"))).toBe(true)

    const freshness = await resolveSealedNarrativeFreshness({
      archiveRoot,
      nowIso: NOW,
    })
    expect(freshness.lastCompleteRunId).toBeNull()
  })
})

describe("chart png confinement", () => {
  it("rejects path traversal chart names", async () => {
    const root = mkdtempSync(join(tmpdir(), "tc-chart-"))
    const writer = new SnapshotWriter(root)
    await expect(writer.writeChartPng("run-1", "../escape", Buffer.from([0x89, 0x50, 0x4e, 0x47, 0, 0, 0, 0])))
      .rejects.toThrow()
  })
})
